name: Generate contribution snake

on:
  schedule:
    - cron: "0 2 * * *" # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sebcrisan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to main
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "chore: update contribution snake"
